[package]
name = "__tests__"
version = "0.1.0"
edition = "2021"

[dependencies]
url = "2.4.1"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
resend-client-rs = { path = "../" }

[dev-dependencies]
mockito = "1.2.0"
